### metodo get
GET http://localhost:4000


### metodo post
POST http://localhost:3001/hackathon
Content-Type: application/json

{
    "nome": "Gustavo",
    "telefone": "34757741"
}

### metodo put
PUT http://localhost:3001/hackathon/123
### metodo patch
PATCH http://localhost:3001/hackathon/123
### metodo delete
DELETE http://localhost:3001/hackathon/123

